// flow-typed signature: 00c44afcae9102ac4307f665d32b92fa
// flow-typed version: <<STUB>>/lodash-decorators_v^5.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash-decorators'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash-decorators' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lodash-decorators/after' {
  declare module.exports: any;
}

declare module 'lodash-decorators/afterAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/Applicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/BindApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/ComposeApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/InvokeApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/MemoizeApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/PartialApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/PartialedApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/PartialValueApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/PostValueApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/PreValueApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/applicators/WrapApplicator' {
  declare module.exports: any;
}

declare module 'lodash-decorators/ary' {
  declare module.exports: any;
}

declare module 'lodash-decorators/attempt' {
  declare module.exports: any;
}

declare module 'lodash-decorators/before' {
  declare module.exports: any;
}

declare module 'lodash-decorators/beforeAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/bind' {
  declare module.exports: any;
}

declare module 'lodash-decorators/bindAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/curry' {
  declare module.exports: any;
}

declare module 'lodash-decorators/curryAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/curryRight' {
  declare module.exports: any;
}

declare module 'lodash-decorators/curryRightAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/debounce' {
  declare module.exports: any;
}

declare module 'lodash-decorators/debounceAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/defer' {
  declare module.exports: any;
}

declare module 'lodash-decorators/delay' {
  declare module.exports: any;
}

declare module 'lodash-decorators/factory' {
  declare module.exports: any;
}

declare module 'lodash-decorators/factory/common' {
  declare module.exports: any;
}

declare module 'lodash-decorators/factory/DecoratorConfig' {
  declare module.exports: any;
}

declare module 'lodash-decorators/factory/DecoratorFactory' {
  declare module.exports: any;
}

declare module 'lodash-decorators/flip' {
  declare module.exports: any;
}

declare module 'lodash-decorators/flow' {
  declare module.exports: any;
}

declare module 'lodash-decorators/flowRight' {
  declare module.exports: any;
}

declare module 'lodash-decorators/memoize' {
  declare module.exports: any;
}

declare module 'lodash-decorators/memoizeAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/mixin' {
  declare module.exports: any;
}

declare module 'lodash-decorators/negate' {
  declare module.exports: any;
}

declare module 'lodash-decorators/once' {
  declare module.exports: any;
}

declare module 'lodash-decorators/onceAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/overArgs' {
  declare module.exports: any;
}

declare module 'lodash-decorators/partial' {
  declare module.exports: any;
}

declare module 'lodash-decorators/partialRight' {
  declare module.exports: any;
}

declare module 'lodash-decorators/rearg' {
  declare module.exports: any;
}

declare module 'lodash-decorators/rest' {
  declare module.exports: any;
}

declare module 'lodash-decorators/shared' {
  declare module.exports: any;
}

declare module 'lodash-decorators/spread' {
  declare module.exports: any;
}

declare module 'lodash-decorators/tap' {
  declare module.exports: any;
}

declare module 'lodash-decorators/throttle' {
  declare module.exports: any;
}

declare module 'lodash-decorators/throttleAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/unary' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/assignAll' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/bind' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/CompositeKeyWeakMap' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/copyMetaData' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/isDecoratorArgs' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/log' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/resolveFunction' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/returnAtIndex' {
  declare module.exports: any;
}

declare module 'lodash-decorators/utils/wrapConstructor' {
  declare module.exports: any;
}

declare module 'lodash-decorators/wrap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lodash-decorators/after.js' {
  declare module.exports: $Exports<'lodash-decorators/after'>;
}
declare module 'lodash-decorators/afterAll.js' {
  declare module.exports: $Exports<'lodash-decorators/afterAll'>;
}
declare module 'lodash-decorators/applicators.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators'>;
}
declare module 'lodash-decorators/applicators/Applicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/Applicator'>;
}
declare module 'lodash-decorators/applicators/BindApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/BindApplicator'>;
}
declare module 'lodash-decorators/applicators/ComposeApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/ComposeApplicator'>;
}
declare module 'lodash-decorators/applicators/InvokeApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/InvokeApplicator'>;
}
declare module 'lodash-decorators/applicators/MemoizeApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/MemoizeApplicator'>;
}
declare module 'lodash-decorators/applicators/PartialApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/PartialApplicator'>;
}
declare module 'lodash-decorators/applicators/PartialedApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/PartialedApplicator'>;
}
declare module 'lodash-decorators/applicators/PartialValueApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/PartialValueApplicator'>;
}
declare module 'lodash-decorators/applicators/PostValueApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/PostValueApplicator'>;
}
declare module 'lodash-decorators/applicators/PreValueApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/PreValueApplicator'>;
}
declare module 'lodash-decorators/applicators/WrapApplicator.js' {
  declare module.exports: $Exports<'lodash-decorators/applicators/WrapApplicator'>;
}
declare module 'lodash-decorators/ary.js' {
  declare module.exports: $Exports<'lodash-decorators/ary'>;
}
declare module 'lodash-decorators/attempt.js' {
  declare module.exports: $Exports<'lodash-decorators/attempt'>;
}
declare module 'lodash-decorators/before.js' {
  declare module.exports: $Exports<'lodash-decorators/before'>;
}
declare module 'lodash-decorators/beforeAll.js' {
  declare module.exports: $Exports<'lodash-decorators/beforeAll'>;
}
declare module 'lodash-decorators/bind.js' {
  declare module.exports: $Exports<'lodash-decorators/bind'>;
}
declare module 'lodash-decorators/bindAll.js' {
  declare module.exports: $Exports<'lodash-decorators/bindAll'>;
}
declare module 'lodash-decorators/curry.js' {
  declare module.exports: $Exports<'lodash-decorators/curry'>;
}
declare module 'lodash-decorators/curryAll.js' {
  declare module.exports: $Exports<'lodash-decorators/curryAll'>;
}
declare module 'lodash-decorators/curryRight.js' {
  declare module.exports: $Exports<'lodash-decorators/curryRight'>;
}
declare module 'lodash-decorators/curryRightAll.js' {
  declare module.exports: $Exports<'lodash-decorators/curryRightAll'>;
}
declare module 'lodash-decorators/debounce.js' {
  declare module.exports: $Exports<'lodash-decorators/debounce'>;
}
declare module 'lodash-decorators/debounceAll.js' {
  declare module.exports: $Exports<'lodash-decorators/debounceAll'>;
}
declare module 'lodash-decorators/defer.js' {
  declare module.exports: $Exports<'lodash-decorators/defer'>;
}
declare module 'lodash-decorators/delay.js' {
  declare module.exports: $Exports<'lodash-decorators/delay'>;
}
declare module 'lodash-decorators/factory.js' {
  declare module.exports: $Exports<'lodash-decorators/factory'>;
}
declare module 'lodash-decorators/factory/common.js' {
  declare module.exports: $Exports<'lodash-decorators/factory/common'>;
}
declare module 'lodash-decorators/factory/DecoratorConfig.js' {
  declare module.exports: $Exports<'lodash-decorators/factory/DecoratorConfig'>;
}
declare module 'lodash-decorators/factory/DecoratorFactory.js' {
  declare module.exports: $Exports<'lodash-decorators/factory/DecoratorFactory'>;
}
declare module 'lodash-decorators/flip.js' {
  declare module.exports: $Exports<'lodash-decorators/flip'>;
}
declare module 'lodash-decorators/flow.js' {
  declare module.exports: $Exports<'lodash-decorators/flow'>;
}
declare module 'lodash-decorators/flowRight.js' {
  declare module.exports: $Exports<'lodash-decorators/flowRight'>;
}
declare module 'lodash-decorators/index' {
  declare module.exports: $Exports<'lodash-decorators'>;
}
declare module 'lodash-decorators/index.js' {
  declare module.exports: $Exports<'lodash-decorators'>;
}
declare module 'lodash-decorators/memoize.js' {
  declare module.exports: $Exports<'lodash-decorators/memoize'>;
}
declare module 'lodash-decorators/memoizeAll.js' {
  declare module.exports: $Exports<'lodash-decorators/memoizeAll'>;
}
declare module 'lodash-decorators/mixin.js' {
  declare module.exports: $Exports<'lodash-decorators/mixin'>;
}
declare module 'lodash-decorators/negate.js' {
  declare module.exports: $Exports<'lodash-decorators/negate'>;
}
declare module 'lodash-decorators/once.js' {
  declare module.exports: $Exports<'lodash-decorators/once'>;
}
declare module 'lodash-decorators/onceAll.js' {
  declare module.exports: $Exports<'lodash-decorators/onceAll'>;
}
declare module 'lodash-decorators/overArgs.js' {
  declare module.exports: $Exports<'lodash-decorators/overArgs'>;
}
declare module 'lodash-decorators/partial.js' {
  declare module.exports: $Exports<'lodash-decorators/partial'>;
}
declare module 'lodash-decorators/partialRight.js' {
  declare module.exports: $Exports<'lodash-decorators/partialRight'>;
}
declare module 'lodash-decorators/rearg.js' {
  declare module.exports: $Exports<'lodash-decorators/rearg'>;
}
declare module 'lodash-decorators/rest.js' {
  declare module.exports: $Exports<'lodash-decorators/rest'>;
}
declare module 'lodash-decorators/shared.js' {
  declare module.exports: $Exports<'lodash-decorators/shared'>;
}
declare module 'lodash-decorators/spread.js' {
  declare module.exports: $Exports<'lodash-decorators/spread'>;
}
declare module 'lodash-decorators/tap.js' {
  declare module.exports: $Exports<'lodash-decorators/tap'>;
}
declare module 'lodash-decorators/throttle.js' {
  declare module.exports: $Exports<'lodash-decorators/throttle'>;
}
declare module 'lodash-decorators/throttleAll.js' {
  declare module.exports: $Exports<'lodash-decorators/throttleAll'>;
}
declare module 'lodash-decorators/unary.js' {
  declare module.exports: $Exports<'lodash-decorators/unary'>;
}
declare module 'lodash-decorators/utils.js' {
  declare module.exports: $Exports<'lodash-decorators/utils'>;
}
declare module 'lodash-decorators/utils/assignAll.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/assignAll'>;
}
declare module 'lodash-decorators/utils/bind.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/bind'>;
}
declare module 'lodash-decorators/utils/CompositeKeyWeakMap.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/CompositeKeyWeakMap'>;
}
declare module 'lodash-decorators/utils/copyMetaData.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/copyMetaData'>;
}
declare module 'lodash-decorators/utils/isDecoratorArgs.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/isDecoratorArgs'>;
}
declare module 'lodash-decorators/utils/log.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/log'>;
}
declare module 'lodash-decorators/utils/resolveFunction.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/resolveFunction'>;
}
declare module 'lodash-decorators/utils/returnAtIndex.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/returnAtIndex'>;
}
declare module 'lodash-decorators/utils/wrapConstructor.js' {
  declare module.exports: $Exports<'lodash-decorators/utils/wrapConstructor'>;
}
declare module 'lodash-decorators/wrap.js' {
  declare module.exports: $Exports<'lodash-decorators/wrap'>;
}
