// flow-typed signature: add38fc01bbab416971e21b64f1de95a
// flow-typed version: <<STUB>>/react-a11y_v^1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-a11y'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-a11y' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-a11y/dist/react-a11y' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/a11y' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/after' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/index' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/options' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/avoid-positive-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/button-role-space' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/hidden-uses-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/img-uses-alt' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/index' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/label-uses-for' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/mouse-events-map-to-key-events' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/no-hash-ref' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/no-unsupported-elements-use-aria' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/onclick-uses-role' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/onclick-uses-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/redundant-alt' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/tabindex-uses-button' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/use-onblur-not-onchange' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/rules/valid-aria-role' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/test' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/aria' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/browser' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/DOM' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/has-prop' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/hidden-from-at' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/index' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/is-interactive' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/listens-to' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/role' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/test-rules' {
  declare module.exports: any;
}

declare module 'react-a11y/lib/util/trueish' {
  declare module.exports: any;
}

declare module 'react-a11y/mkdocs' {
  declare module.exports: any;
}

declare module 'react-a11y/src/a11y' {
  declare module.exports: any;
}

declare module 'react-a11y/src/after' {
  declare module.exports: any;
}

declare module 'react-a11y/src/index' {
  declare module.exports: any;
}

declare module 'react-a11y/src/options' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/avoid-positive-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/button-role-space' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/hidden-uses-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/img-uses-alt' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/index' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/label-uses-for' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/mouse-events-map-to-key-events' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/no-access-key' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/no-hash-ref' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/no-unsupported-elements-use-aria' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/onclick-uses-role' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/onclick-uses-tabindex' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/redundant-alt' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/tabindex-uses-button' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/use-onblur-not-onchange' {
  declare module.exports: any;
}

declare module 'react-a11y/src/rules/valid-aria-role' {
  declare module.exports: any;
}

declare module 'react-a11y/src/test' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/aria' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/browser' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/DOM' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/has-prop' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/hidden-from-at' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/index' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/is-interactive' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/listens-to' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/role' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/test-rules' {
  declare module.exports: any;
}

declare module 'react-a11y/src/util/trueish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-a11y/dist/react-a11y.js' {
  declare module.exports: $Exports<'react-a11y/dist/react-a11y'>;
}
declare module 'react-a11y/lib/a11y.js' {
  declare module.exports: $Exports<'react-a11y/lib/a11y'>;
}
declare module 'react-a11y/lib/after.js' {
  declare module.exports: $Exports<'react-a11y/lib/after'>;
}
declare module 'react-a11y/lib/index.js' {
  declare module.exports: $Exports<'react-a11y/lib/index'>;
}
declare module 'react-a11y/lib/options.js' {
  declare module.exports: $Exports<'react-a11y/lib/options'>;
}
declare module 'react-a11y/lib/rules/avoid-positive-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/avoid-positive-tabindex'>;
}
declare module 'react-a11y/lib/rules/button-role-space.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/button-role-space'>;
}
declare module 'react-a11y/lib/rules/hidden-uses-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/hidden-uses-tabindex'>;
}
declare module 'react-a11y/lib/rules/img-uses-alt.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/img-uses-alt'>;
}
declare module 'react-a11y/lib/rules/index.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/index'>;
}
declare module 'react-a11y/lib/rules/label-uses-for.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/label-uses-for'>;
}
declare module 'react-a11y/lib/rules/mouse-events-map-to-key-events.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/mouse-events-map-to-key-events'>;
}
declare module 'react-a11y/lib/rules/no-access-key.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/no-access-key'>;
}
declare module 'react-a11y/lib/rules/no-hash-ref.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/no-hash-ref'>;
}
declare module 'react-a11y/lib/rules/no-unsupported-elements-use-aria.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/no-unsupported-elements-use-aria'>;
}
declare module 'react-a11y/lib/rules/onclick-uses-role.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/onclick-uses-role'>;
}
declare module 'react-a11y/lib/rules/onclick-uses-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/onclick-uses-tabindex'>;
}
declare module 'react-a11y/lib/rules/redundant-alt.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/redundant-alt'>;
}
declare module 'react-a11y/lib/rules/tabindex-uses-button.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/tabindex-uses-button'>;
}
declare module 'react-a11y/lib/rules/use-onblur-not-onchange.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/use-onblur-not-onchange'>;
}
declare module 'react-a11y/lib/rules/valid-aria-role.js' {
  declare module.exports: $Exports<'react-a11y/lib/rules/valid-aria-role'>;
}
declare module 'react-a11y/lib/test.js' {
  declare module.exports: $Exports<'react-a11y/lib/test'>;
}
declare module 'react-a11y/lib/util/aria.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/aria'>;
}
declare module 'react-a11y/lib/util/browser.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/browser'>;
}
declare module 'react-a11y/lib/util/DOM.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/DOM'>;
}
declare module 'react-a11y/lib/util/has-prop.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/has-prop'>;
}
declare module 'react-a11y/lib/util/hidden-from-at.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/hidden-from-at'>;
}
declare module 'react-a11y/lib/util/index.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/index'>;
}
declare module 'react-a11y/lib/util/is-interactive.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/is-interactive'>;
}
declare module 'react-a11y/lib/util/listens-to.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/listens-to'>;
}
declare module 'react-a11y/lib/util/role.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/role'>;
}
declare module 'react-a11y/lib/util/test-rules.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/test-rules'>;
}
declare module 'react-a11y/lib/util/trueish.js' {
  declare module.exports: $Exports<'react-a11y/lib/util/trueish'>;
}
declare module 'react-a11y/mkdocs.js' {
  declare module.exports: $Exports<'react-a11y/mkdocs'>;
}
declare module 'react-a11y/src/a11y.js' {
  declare module.exports: $Exports<'react-a11y/src/a11y'>;
}
declare module 'react-a11y/src/after.js' {
  declare module.exports: $Exports<'react-a11y/src/after'>;
}
declare module 'react-a11y/src/index.js' {
  declare module.exports: $Exports<'react-a11y/src/index'>;
}
declare module 'react-a11y/src/options.js' {
  declare module.exports: $Exports<'react-a11y/src/options'>;
}
declare module 'react-a11y/src/rules/avoid-positive-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/avoid-positive-tabindex'>;
}
declare module 'react-a11y/src/rules/button-role-space.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/button-role-space'>;
}
declare module 'react-a11y/src/rules/hidden-uses-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/hidden-uses-tabindex'>;
}
declare module 'react-a11y/src/rules/img-uses-alt.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/img-uses-alt'>;
}
declare module 'react-a11y/src/rules/index.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/index'>;
}
declare module 'react-a11y/src/rules/label-uses-for.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/label-uses-for'>;
}
declare module 'react-a11y/src/rules/mouse-events-map-to-key-events.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/mouse-events-map-to-key-events'>;
}
declare module 'react-a11y/src/rules/no-access-key.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/no-access-key'>;
}
declare module 'react-a11y/src/rules/no-hash-ref.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/no-hash-ref'>;
}
declare module 'react-a11y/src/rules/no-unsupported-elements-use-aria.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/no-unsupported-elements-use-aria'>;
}
declare module 'react-a11y/src/rules/onclick-uses-role.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/onclick-uses-role'>;
}
declare module 'react-a11y/src/rules/onclick-uses-tabindex.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/onclick-uses-tabindex'>;
}
declare module 'react-a11y/src/rules/redundant-alt.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/redundant-alt'>;
}
declare module 'react-a11y/src/rules/tabindex-uses-button.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/tabindex-uses-button'>;
}
declare module 'react-a11y/src/rules/use-onblur-not-onchange.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/use-onblur-not-onchange'>;
}
declare module 'react-a11y/src/rules/valid-aria-role.js' {
  declare module.exports: $Exports<'react-a11y/src/rules/valid-aria-role'>;
}
declare module 'react-a11y/src/test.js' {
  declare module.exports: $Exports<'react-a11y/src/test'>;
}
declare module 'react-a11y/src/util/aria.js' {
  declare module.exports: $Exports<'react-a11y/src/util/aria'>;
}
declare module 'react-a11y/src/util/browser.js' {
  declare module.exports: $Exports<'react-a11y/src/util/browser'>;
}
declare module 'react-a11y/src/util/DOM.js' {
  declare module.exports: $Exports<'react-a11y/src/util/DOM'>;
}
declare module 'react-a11y/src/util/has-prop.js' {
  declare module.exports: $Exports<'react-a11y/src/util/has-prop'>;
}
declare module 'react-a11y/src/util/hidden-from-at.js' {
  declare module.exports: $Exports<'react-a11y/src/util/hidden-from-at'>;
}
declare module 'react-a11y/src/util/index.js' {
  declare module.exports: $Exports<'react-a11y/src/util/index'>;
}
declare module 'react-a11y/src/util/is-interactive.js' {
  declare module.exports: $Exports<'react-a11y/src/util/is-interactive'>;
}
declare module 'react-a11y/src/util/listens-to.js' {
  declare module.exports: $Exports<'react-a11y/src/util/listens-to'>;
}
declare module 'react-a11y/src/util/role.js' {
  declare module.exports: $Exports<'react-a11y/src/util/role'>;
}
declare module 'react-a11y/src/util/test-rules.js' {
  declare module.exports: $Exports<'react-a11y/src/util/test-rules'>;
}
declare module 'react-a11y/src/util/trueish.js' {
  declare module.exports: $Exports<'react-a11y/src/util/trueish'>;
}
