// flow-typed signature: a7082e946c8403bdffd9962121fbed7e
// flow-typed version: <<STUB>>/redux-act-async_v^1.7.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-act-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-act-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-act-async/lib/createActionAsync' {
  declare module.exports: any;
}

declare module 'redux-act-async/lib/createReducerAsync' {
  declare module.exports: any;
}

declare module 'redux-act-async/lib/index' {
  declare module.exports: any;
}

declare module 'redux-act-async/src/createActionAsync' {
  declare module.exports: any;
}

declare module 'redux-act-async/src/createReducerAsync' {
  declare module.exports: any;
}

declare module 'redux-act-async/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-act-async/lib/createActionAsync.js' {
  declare module.exports: $Exports<'redux-act-async/lib/createActionAsync'>;
}
declare module 'redux-act-async/lib/createReducerAsync.js' {
  declare module.exports: $Exports<'redux-act-async/lib/createReducerAsync'>;
}
declare module 'redux-act-async/lib/index.js' {
  declare module.exports: $Exports<'redux-act-async/lib/index'>;
}
declare module 'redux-act-async/src/createActionAsync.js' {
  declare module.exports: $Exports<'redux-act-async/src/createActionAsync'>;
}
declare module 'redux-act-async/src/createReducerAsync.js' {
  declare module.exports: $Exports<'redux-act-async/src/createReducerAsync'>;
}
declare module 'redux-act-async/src/index.js' {
  declare module.exports: $Exports<'redux-act-async/src/index'>;
}
